### ISSUE TITLE
tremc doesn't run

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#572]
```
 [kronikpillow@susanoo ~]$ tremc
/usr/bin/tremc:99: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  config = configparser.SafeConfigParser()
Traceback (most recent call last):
  File "/usr/bin/tremc", line 3711, in <module>
    Interface()
  File "/usr/bin/tremc", line 985, in __init__
    self.run()
  File "/usr/bin/tremc", line 1079, in run
    self.draw_stats()
  File "/usr/bin/tremc", line 2615, in draw_stats
    self.draw_global_rates()
  File "/usr/bin/tremc", line 2694, in draw_global_rates
    self.screen.addch(curses.ACS_UARROW, curses.A_REVERSE)
_curses.error: addch() returned ERR
```

fresh larbs install

**Comment by LukeSmithxyz** [comment]
Use `tremc-git`. I believe there's an error wth standard `tremc` right now.

**Comment by kronikpillow** [comment]
yup that solved it, maybe change it in LARBS to tremc-git until it's fixed

**Comment by LukeSmithxyz** [comment]
Well as is, the little warning message from the `ifinstalled` script
will only be searching for specific commands, not package names, so I'd
have to change how that works.

**Comment by LukeSmithxyz** [comment]
Changed it to demand a specific program installed.
